services:
  node-a:
    build:
      context: .
      dockerfile: docker/Dockerfile
    hostname: node-a
    command: ["start"]
    ports:
      - "17790:7789"

  node-b:
    build:
      context: .
      dockerfile: docker/Dockerfile
    hostname: node-b
    command: ["start"]
    ports:
      - "17791:7789"
